add some points
mr-mig/going-to-production pull request #3
Opened 2016-11-27 15:34 UTC by restrry

2016-11-27 15:35 UTC, restrry commented on spa-checklist.md
> + - [ ] My app has a assets cache-busting implemented
could be moved into `Assets` section?

2016-11-28 11:29 UTC, kirillDanshin commented on spa-checklist.md
> + - [ ] My app has a assets cache-busting implemented
why you replace this line?

2016-12-02 22:08 UTC, mr-mig commented on spa-checklist.md
> + - [ ] Have a maintenance page
What is a "maintenance page"?

2016-12-02 22:54 UTC, mr-mig commented on spa-checklist.md
> + - [ ] My app has a assets cache-busting implemented
Please, remove an article in the sentence: 
"My app has assets cache-busting implemented"

2016-12-02 22:55 UTC, mr-mig commented on spa-checklist.md
> + - [ ] My app has a assets cache-busting implemented
I'd leave this line here, as asset cache-busting is essential for sane versioning

2016-12-02 22:55 UTC, mr-mig commented on spa-checklist.md
> + - [ ] Error storage process sourcemaped files
Great additions overall, thank you 👍

2016-12-03 16:11 UTC, kirillDanshin commented on spa-checklist.md
> + - [ ] Have a maintenance page
@mr-mig "Sorry, we'll back ASAP, you can now go for a coffee-break and refresh this page than"

2016-12-03 16:14 UTC, kirillDanshin commented on spa-checklist.md
> + - [ ] My app has a assets cache-busting implemented
@restrry @mr-mig I think we need to leave booth lines or replace this with
"My app has a cache-busting implemented (assets, object cache etc.)"

2016-12-03 21:23 UTC, mr-mig commented on spa-checklist.md
> + - [ ] My app has a assets cache-busting implemented
> "My app has a cache-busting implemented (assets, object cache etc.)"
:+1:

2016-12-03 21:23 UTC, mr-mig commented on spa-checklist.md
> + - [ ] Have a maintenance page
Could you please add it to the description?

2016-12-05 19:19 UTC, restrry commented
@kirillDanshin @mr-mig addressed, pls have a look

2016-12-06 19:12 UTC, kirillDanshin requested changes

2016-12-06 19:12 UTC, kirillDanshin commented on spa-checklist.md
> + - [ ] My app has a cache-busting implemented (assets, object cache etc.)
👍

2016-12-06 19:12 UTC, kirillDanshin commented on spa-checklist.md
> + - [ ] My app is passing performance tests with high grades
we need to add
`- [ ] My app is loading in less than 3 seconds`

2016-12-06 19:12 UTC, kirillDanshin commented on spa-checklist.md
> +    - [ ] OWASP Top 10 Vulnerabilities
maybe add a link? https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project or https://www.owasp.org/index.php/OWASP_Top_Ten_Cheat_Sheet

2016-12-07 08:50 UTC, merged

2016-12-07 08:50 UTC, mr-mig commented
Merged. Thanks, great additions!

2016-12-07 08:51 UTC, mr-mig commented
@kirillDanshin I'll add your comments manually

2016-12-07 09:03 UTC, restrry commented on spa-checklist.md
> + - [ ] My app is passing performance tests with high grades
Probably makes sense to add link to [RAIL model](https://developers.google.com/web/fundamentals/performance/rail) in that case